<?php

/**
 * Implements hook_default_search_api_index_alter().
 *
 * Change the default search api index from features/ulf_search_settings
 */
function ulf_aarhus_settings_default_search_api_index_alter(&$defaults) {
  // Change search filter role for user index. Role ID for aarhus differs from other sites.
  unset($defaults['users']->options['data_alter_callbacks']['search_api_alter_role_filter']['settings']['roles'][3]);
  $defaults['users']->options['data_alter_callbacks']['search_api_alter_role_filter']['settings']['roles'][18] = '18';
}

/**
 * Implements hook_mail_alter().
 */
function ulf_aarhus_settings_mail_alter(&$message) {
  $default_from = variable_get('site_mail', ini_get('sendmail_from'));
  $message['from'] = 'ULF i Aarhus <' . $default_from . '>';
  $message['headers']['From'] = $message['headers']['Sender'] = $message['headers']['Return-Path'] = $message['headers']['Errors-To'] = $message['from'];

  if (empty($message['headers']['Reply-to'])) {
    $message['headers']['Reply-To'] = $message['from'];
  }
}

/**
 * Implements hook_video_embed_handler_info_alter().
 */
function ulf_aarhus_settings_video_embed_handler_info_alter(&$info) {
  $info['youtube']['function'] = '_ulf_aarhus_settings_youtube_embed';
  $info['vimeo']['function'] = '_ulf_aarhus_settings_vimeo_embed';
}

/**
 * Custom youtube embed handler.
 * Grabbed from video_embed_field/video_embed_field.handlers.inc and added
 * consent attributes.
 *
 * @param $url
 * @param $settings
 *
 * @return array
 */
function _ulf_aarhus_settings_youtube_embed($url, $settings) {
  $output = array();

  if(preg_match('/#t=((?P<min>\d+)m)?((?P<sec>\d+)s)?((?P<tinsec>\d+))?/', $url, $matches)){
    if(isset($matches['tinsec'])){
      $settings['start'] = $matches['tinsec']; // url already in form #t=125 for 2 minutes and 5 seconds
    } else {
      // url in form #t=2m5s or with other useless data, this is why we still keep adding the default data..
      // give it some default data in case there is no #t=...
      $matches += array(
        "min" => 0,
        "sec" => 0,
      );
      if ($time = ($matches["min"] * 60) + $matches["sec"]) {
        $settings['start'] = $time;
      }
    }
  }

  $id = _video_embed_field_get_youtube_id($url);
  if (!$id) {
    // We can't decode the URL - just return the URL as a link.
    $output['#markup'] = l($url, $url);
    return $output;
  }

  // Add class to variable to avoid adding it to URL param string.
  $class = $settings['class'];
  unset($settings['class']);

  // Construct the embed code.
  $settings['wmode'] = 'opaque';
  $settings_str = urlencode(_video_embed_code_get_settings_str($settings));

  $output['#markup'] = '<iframe src="" data-category-consent="cookie_cat_statistic" class="' . check_plain($class) . '" width="' . check_plain($settings['width']) . '" height="' . check_plain($settings['height']) . '" data-consent-src="//www.youtube.com/embed/' . $id . '?' . $settings_str . '" frameborder="0" allowfullscreen></iframe>';

  return $output;
}

/**
 * Custom vimeo embed handler.
 * Grabbed from video_embed_field/video_embed_field.handlers.inc and added
 * consent attributes.
 *
 * @param $url
 * @param $settings
 *
 * @return array
 */
function _ulf_aarhus_settings_vimeo_embed($url, $settings) {
  $vimeo_data = _video_embed_field_get_vimeo_data($url);

  // Get ID of video from URL.
  $id = _video_embed_field_get_vimeo_id($vimeo_data);

  if (empty($id)) {
    return array(
      '#markup' => l($url, $url),
    );
  }

  // Construct the embed code.
  $settings['player_id'] = drupal_html_id('vimeo-' . $id);
  if (!empty($settings['froogaloop'])) {
    $settings['api'] = 1;
  }
  unset($settings['froogaloop']);

  // Add class to variable to avoid adding it to URL param string.
  $class = $settings['class'];
  unset($settings['class']);

  $settings_str = _video_embed_code_get_settings_str($settings);

  return array(
    '#markup' => '<iframe src="" data-category-consent="cookie_cat_statistic" class="' . check_plain($class) . '" id="' . $settings['player_id'] . '" width="' . check_plain($settings['width']) . '" height="' . check_plain($settings['height']) . '" data-consent-src="//player.vimeo.com/video/' . $id .
      '?' . $settings_str . '" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowfullscreen></iframe>',
  );
}

function ulf_aarhus_settings_views_post_execute(&$view) {
  if ($view->name == 'ulf_courses') {
    foreach ($view->result as $result) {
      if (!empty($result->field_field_collection_price)) {
        $entity = reset($result->field_field_collection_price[0]['rendered']['entity']['field_collection_item']);
        $price = $entity['field_price'][0]['#markup'] . ',- ' . $entity['field_unit_price'][0]['#markup'] . ' (' . $entity['field_moms'][0]['#markup'] .')';
        $result->field_field_collection_price[0]['rendered']['#markup'] = $price;
      }

    }
  }
}

/**
 * Hide buttons for all roles except for editors
 */
/**
 * Implements hook_form_alter().
 */
function ulf_aarhus_settings_form_course_node_form_alter(&$form, &$form_state) {
  global $user;

  if (!in_array('editor', $user->roles, false)) {
    $form['field_practical_info_buttons']['#access'] = FALSE;
  }
}

/**
 * Implements hook_menu().
 */
function ulf_aarhus_settings_menu() {
  $items = [];

  $items['admin/ulfiaarhus/update_show_free_courses_request'] = [
    'title' => 'Select checkbox "show_free_course_request" for all courses that are not free',
    'description' => 'Select checkbox "show_free_course_request" for all courses that are not free',
    'page callback' => 'ulf_aarhus_settings_update_non_free_courses',
    'page arguments' => [],
    'access arguments' => ['access administration pages']
  ];

  return $items;
}

/**
 * Select checkbox "show_free_course_request" for all courses that are not free batch
 */
function ulf_aarhus_settings_update_non_free_courses() {

  $query = db_select('node', 'n');
  $query->fields('n', array('nid'));
  $query->condition('type', 'course');
  $query->join('taxonomy_index', 'term', 'n.nid = term.nid');
  $query->condition('term.tid', 149, '!=');
  $query->join('field_data_field_free', 'field_free', 'n.nid = field_free.entity_id');
  $query->condition('field_free.field_free_value', 1, '!=');
  $results = $query->execute()->fetchAll();

  $batch = array(
    'operations' => array(),
    'finished' => 'ulf_aarhus_settings_update_non_free_courses_finished', // runs after batch is finished
    'title' => t('Updating courses'),
    'init_message' => t('Courses updates is starting.'),
    'progress_message' => t('Updating @current out of @total.'),
    'error_message' => t('Courses updates has encountered an error.'),
  );
  $progress = 0; // where to start
  $limit = 100; // how many to process for each run
  $max = count($results); // how many records to process until stop
  while ($progress <= $max) {
    $batch['operations'][] = array('ulf_aarhus_settings_update_non_free_courses_process', array($progress, $limit));
    $progress = $progress + $limit;
  }
  batch_set($batch);
  batch_process('admin/ulfiaarhus/update_show_free_courses_request'); // page to return to after complete
}

// this is what runs multiple times per batch
function ulf_aarhus_settings_update_non_free_courses_process($progress, $limit, &$context) {

  $query = db_select('node', 'n');
  $query->fields('n', array('nid'));
  $query->condition('type', 'course');
  $query->join('taxonomy_index', 'term', 'n.nid = term.nid');
  $query->condition('term.tid', 149, '!=');
  $query->join('field_data_field_free', 'field_free', 'n.nid = field_free.entity_id');
  $query->condition('field_free.field_free_value', 1, '!=');
  $query->orderBy('n.nid', 'ASC');
  $query->range($progress, $limit);
  $results = $query->execute()->fetchAll();

  $array = [];
  foreach ($results as $item) {
    $array[] = $item->nid;
    $course_nodes = node_load($item->nid);
    $course_nodes->field_practical_info_buttons[LANGUAGE_NONE][1]['value'] = 'show_free_course_request';
    node_save($course_nodes);
  }

  // update progress for message
  $progress = $progress + $limit;
  // update message during each run so you know where you are in the process
  $context['message'] = 'Now processing ' . $progress . ' - ' . $context['results'][0] . ' updated';
}

function ulf_aarhus_settings_update_non_free_courses_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message('Courses updates is complete');
  }
  else {
    $error_operation = reset($operations);
    $message = t('An error occurred while updating %error_operation with arguments: @arguments', array(
      '%error_operation' => $error_operation[0],
      '@arguments' => print_r($error_operation[1], TRUE)
    ));
    drupal_set_message($message, 'error');
  }
}
